### ISSUE TITLE
jsduck 6 after generate not exist doc

### ISSUE THREAD

**Issue by cybermerlin** [senchalabs/jsduck#623]
in directory Source exists files *.html, but in to directory Output only for base class js-file (array.js, object.js,...)
my conf
{
    "--": ["main/apps/userprofile/js","main/apps/desktop/js","sa"],
    "--title": "JavaScript FrameWorks",
    "--output": "docs",
    "--ignore-global":true,
    "--warnings": [
        "-nodoc",
        "-link",
        "-type_name",
        "-html"
    ],
    "--images": "docs/img",
    "--builtin-classes": true,
    "--seo": true
}

url project
https://bitbucket.org/nocproject/noc

**Comment by nene** [comment]
Sorry, I don't understand your problem.

**Comment by cybermerlin** [comment]
I launched a jsduck with config (on my first post)
was generated html files, but in browser on page not exists this html

please run jsduck for https://bitbucket.org/nocproject/noc   and you see all

**Comment by nene** [comment]
OK, I see what's your problem.

JSDuck only detects classes that have a doc-comment. In your code there isn't a single doc-comment to be found, so JSDuck outputs no documentation. It does output all the scanned JS source code as HTML just in case to source/ dir.

Just add some documentation to your classes, and JSDuck will find them. You should also add doc-comments to public methods, otherwise JSDuck will treat them as private and hide by default. For example:

```js
/**
 * Login window.
 */
Ext.define("NOC.main.desktop.Login", {
    ...
});
```
