### ISSUE TITLE
jsduck: command not found

### ISSUE THREAD

**Issue by nuri-engin** [senchalabs/jsduck#673]
I've completed required installation for jsduck and now it's exist on `˜/.gem/ruby/2.0.0/gems/jsduck-5.3.4` 

and includes those files:
`COPYING, README.md, bin, js-classes, lib, template-min` 

but when runing this command;
`jsduck sencha-sdks/ext-6.5.2/build Dev/myapp/ --output docs`

it returns this error;
`jsduck: command not found`

I'm using MacOS and couldn't figure out what is missing here?

**Comment by nene** [comment]
The problem is that the directory that contains `jsduck` executable is not in your `$PATH`. Check what it contains:

    echo $PATH

You likely have a general problem with installing Ruby gems. Search the web for general problem of installing them as executables. For example: https://stackoverflow.com/questions/2392293/ruby-gems-returns-command-not-found

**Comment by nuri-engin** [comment]
Dear @nene I've added this path to $PATH variable: `export PATH=$PATH:˜/.gem/ruby/2.0.0/gems/jsduck.5.3.4`

and this is response of $PATH command; `-bash: /Applications/Sencha/Test/2_1_2_1/stc:/Users/frontend/bin/Sencha/Cmd:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/frontend/.rvm/bin:˜/.gem/ruby/2.0.0/gems/jsduck.5.3.4: No such file or directory`

so even I have the `jsduck` path in the variable, still it says **command-not-found**.
